### ISSUE TITLE
Create page for showing training games by game identifier

### ISSUE THREAD

**Issue by johannesdolk** [cygni/snakebot-webclient#16]
We are going to rework how training mode works, instead of a specific page with a game, the server will provide a link to a specific page (with unique id) where the game can be accessed/viewed. 
This means some refactoring/writing of current logics.

But we'll start with a just a page and work from there.

**Comment by lenkan** [comment]
I suggest the following routes:

- **/games/** - Shows the list of active games. For now, just the identifiers. In the future this view may be extended to enable searching for old games etc. So, basically the same as the current start page.
- **/games/{id}** - Shows the _board_ for the game with the specified id. Currently, this would only support live games. From here the user may:
    - Start and pause/play game.
    - View current bots and their points.
    - Choose play speed.

We can start to implement this without having the server provide a link. When you run your test-game, just make sure that the bot-client is not starting the game automatically. Then use the game identifier provided by the server for the route.

If we disregard the UX for now, it seems like most of this is already implemented, we just need to adjust the routes and change the way we handle the _active_ game.

**Comment by emilb** [comment]
One aspect to consider is that we probably don't want to expose a list of all available gameID's. The reason behind the client getting an URL for starting/watching a game is that it should be private. One doesn't really want another person messing up a game.

**Comment by johannesdolk** [comment]
finished, waiting on pull-request
