### ISSUE TITLE
Handling of invalid tokens

### ISSUE THREAD

**Issue by emilb** [cygni/snakebot-webclient#28]
If the client's token has been revoked (or just timed out) the server will reply with a message called Unauthorized. This message has a property called errorMessage. 

If this happens the application should clear it's local storage of the token and enter a state of "Not logged in". Perhaps even present the login page.

**Comment by jndev90** [comment]
Added mapping for se.cygni.snake.eventapi.exception.Unauthorized socket message. User credentials will be removed from local storage and the user will be redirected to the auth page if token is invalid.
