### ISSUE TITLE
Make server websocket adress configurable

### ISSUE THREAD

**Issue by emilb** [cygni/snakebot-webclient#6]
Now the adress to the websocket is hard coded in TournamentStore.js and GameStore.js. For deployment we need this adress to either be specified as an environment variable or a configuration file.

**Comment by emilb** [comment]
A note on the above issue: To be able to deploy this application in Docker we need some stuff configurable. Also, the way it is started now seems to be for development mode only. We need to investigate how to package and run this application in production mode. Logging to stdout etc.

Please consider prioritizing this issue so we can get a pipeline for CD up and running!

**Comment by lenkan** [comment]
I have figured out how to make this thing configurable. But at what level to we want to configure? Do we want to pass the socket-url in the 'npm start' command? Do we want to pass it when creating the docket image? The particular use case would be helpful.

**Comment by emilb** [comment]
Anything we want to be able to pass from the Docker run command we would ideally want to be configurable. Right now I can only think of one thing:
snakeserverhost: snake.cygni.se (default)

By being able to specify the snake server host it is possible to run the docker container against arbitrary server.

The actual path to the websockets (there are two in use, or?) could also be configurable but they should have default values.
