### ISSUE TITLE
Create a loginpage

### ISSUE THREAD

**Issue by emilb** [cygni/snakebot-webclient#7]
Create a loginpage to access tournament settings

**Comment by johannesdolk** [comment]
A simple loginpage with a token-handler implemented with react-router

**Comment by emilb** [comment]
vi har nu lagt till en logintjänst som returnerar ett token vid lyckad login. Detta token ska inkluderas i alla requests som har med Tournaments att göra. 

Login är ett GET eller POST mot:
http://localhost:8080/login?login=emil&password=lime

och returnerar ett token:
cfbb8d95-17c3-46ee-831e-1a486ec032e6

Följande login är nu hårdkodade:
put("emil", "lime");
put("chen", "nehc");
put("johannes", "sennahoj");

Detta token används alltså sedan i de JSON-objekt som går över websocketen.

Det går nu att:
KillTournament
CreateTournament
UpdateTournamentSettings
StartTournamentGame

**Comment by jndev90** [comment]
Implemented token based login page and made tournament components protected with react router.
Token are saved in local storage and added to socket requests.
