### ISSUE TITLE
Performance issues rendering a game

### ISSUE THREAD

**Issue by emilb** [cygni/snakebot-webclient#8]
There is a significant amount of lag when rendering large games. 

Perhaps a good strategy would be to store (in memory och local storage) all the game events in their JSON-format and start the rendering when enough (or all) events have been received.

**Comment by jonasohrn** [comment]
Refactoring GameBoard.js and TileUtils.js to get better performance.
Also adding unit tests to verify old & new code give same output, see http://x-team.com/2016/05/setting-up-javascript-testing-tools-for-es6/

**Comment by jonasohrn** [comment]
In my test, a big map 100x100 with 10 snakes, the exec time went down from approx 70 to 7 ms.
Still there is an initial delay a couple of seconds after starting the game.

**Comment by emilb** [comment]
That's great! Please create a pull request so we can merge and deploy!
